# We want Exclude directives from different
# config files to get merged, not overwritten
inherit_mode:
  merge:
    - Exclude

require:
  # Standard's config uses custom cops,
  # so it must be loaded
  - standard
  - rubocop-rspec
  - rubocop-performance

inherit_gem:
  standard: config/base.yml

# Metrics:
#   Enabled: true

# Global options, like Ruby version
AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2

# Exclude:
RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false
